### ISSUE TITLE
[1.15.2] mod does not load defaultconfig

### ISSUE THREAD

**Issue by realTIMematrix** [thraaawn/RiddleChests#3]
Hi,

i'm using:

- Minecraft: 1.15.2
- Forge: 31.0.14
- RiddleChests-1.1.0.1.jar
- libnonymous-1.15.2-1.1.0.2

After starting a fresh pack i recognized that the mod creates two different config files.
riddlechests-client.toml + riddlechests-common.toml.

After moving these two files from the config folder to the defaultconfig folder only the riddlechests-common.toml file was created again. it seems that only the riddlechests-client.toml will be loaded from the defaultconfig folder and not the other one which is not expected.

**Comment by davenonymous** [comment]
The client config of the mod is currently empty. Maybe that's why forge isn't copying it from the default folder. Or did you only run it on a server?
Forge simply copies files from the default folder to the config folder if the config file does not exist already.

**Comment by realTIMematrix** [comment]
> The client config of the mod is currently empty. Maybe that's why forge isn't copying it from the default folder. Or did you only run it on a server?

I did not run it on a server. I used only my Client. 

> Forge simply copies files from the default folder to the config folder if the config file does not exist already.

I know this and i like this feature because modpack creators can easy deploy default config files that matches to their pack.

But in your mod the empty file (riddlechests-client.toml) will be loaded from the default config folder.

The riddlechests-common.toml file will created every time, no matter if I haved a file in the defaultconfig folder or not. And that is the issue. In my opinion your mod should check for both files if they are in the defaultconfig or not. it is useless to check only the empty file and not the file which has values...

**Comment by davenonymous** [comment]
I have no idea what you mean by "But in your mod the empty file (riddlechests-client.toml) will be loaded from the default config folder." It's an empty config. There is nothing to get loaded there. How do you even know it gets loaded?

Neither do I understand this: "The riddlechests-common.toml file will created every time, no matter if I haved a file in the defaultconfig folder or not." Of course it will be created every time. If you have a file in the the defaultconfig folder it will simply copy over that file, otherwise it will create the file with the defaults from the mod.

Also: I'm not actually doing anything, I'm just registering both configs with Forge. In the same manner. I'm not specifying any file names or places where to save or load them from. Most mods have this exact same behavior.

**Comment by realTIMematrix** [comment]
Ok, you can close the ticket if you want.
